# Generated by Django 6.0 on 2025-12-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PROJECT_SUBMITTED', 'Project Submitted'), ('PROJECT_APPROVED', 'Project Approved'), ('PROJECT_REJECTED', 'Project Rejected'), ('PROJECT_NEEDS_CHANGES', 'Project Needs Changes'), ('ACCESS_REQUESTED', 'Access Requested'), ('ACCESS_APPROVED', 'Access Approved'), ('ACCESS_REJECTED', 'Access Rejected'), ('ACCESS_REVOKED', 'Access Revoked'), ('INVESTMENT_SUCCESS', 'Investment Success'), ('INVESTMENT_FAILED', 'Investment Failed'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('NEW_ACCESS_REQUEST', 'New Access Request')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_id', models.CharField(blank=True, max_length=255, null=True)),
                ('related_type', models.CharField(blank=True, choices=[('project', 'Project'), ('access_request', 'Access Request'), ('investment', 'Investment'), ('payment', 'Payment')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
