# Generated by Django 6.0 on 2026-01-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_type',
            field=models.CharField(blank=True, choices=[('project', 'Project'), ('access_request', 'Access Request'), ('investment', 'Investment'), ('payment', 'Payment'), ('project_edit_request', 'Project Edit Request'), ('project_archive_request', 'Project Archive Request'), ('user', 'User')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PROJECT_SUBMITTED', 'Project Submitted'), ('PROJECT_APPROVED', 'Project Approved'), ('PROJECT_REJECTED', 'Project Rejected'), ('PROJECT_NEEDS_CHANGES', 'Project Needs Changes'), ('PROJECT_EDIT_REQUESTED', 'Project Edit Requested'), ('PROJECT_EDIT_APPROVED', 'Project Edit Approved'), ('PROJECT_EDIT_REJECTED', 'Project Edit Rejected'), ('PROJECT_ARCHIVE_REQUESTED', 'Project Archive Requested'), ('PROJECT_ARCHIVE_APPROVED', 'Project Archive Approved'), ('PROJECT_ARCHIVE_REJECTED', 'Project Archive Rejected'), ('ACCESS_REQUESTED', 'Access Requested'), ('ACCESS_APPROVED', 'Access Approved'), ('ACCESS_REJECTED', 'Access Rejected'), ('ACCESS_REVOKED', 'Access Revoked'), ('INVESTMENT_REQUESTED', 'Investment Requested'), ('INVESTMENT_APPROVED', 'Investment Approved'), ('INVESTMENT_REJECTED', 'Investment Rejected'), ('INVESTMENT_EXPIRED', 'Investment Expired'), ('INVESTMENT_PROCESSING', 'Investment Processing'), ('INVESTMENT_COMPLETED', 'Investment Completed'), ('INVESTMENT_REFUNDED', 'Investment Refunded'), ('INVESTMENT_WITHDRAWN', 'Investment Withdrawn'), ('INVESTMENT_REVERSED', 'Investment Reversed'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('NEW_ACCESS_REQUEST', 'New Access Request'), ('USER_BANNED', 'User Banned')], max_length=50),
        ),
    ]
