# Generated by Django 6.0 on 2025-12-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('REAL_ESTATE', 'Real Estate'), ('ENERGY', 'Energy'), ('HEALTHCARE', 'Healthcare'), ('AGRICULTURE', 'Agriculture'), ('MANUFACTURING', 'Manufacturing'), ('RETAIL', 'Retail'), ('SERVICES', 'Services'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_CHANGES', 'Needs Changes'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_shares', models.PositiveIntegerField()),
                ('shares_sold', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('has_3d_model', models.BooleanField(default=False)),
                ('model_3d_url', models.URLField(blank=True, null=True)),
                ('is_3d_public', models.BooleanField(default=False)),
                ('has_restricted_fields', models.BooleanField(default=False)),
                ('financial_projections', models.TextField(blank=True, null=True)),
                ('business_plan', models.TextField(blank=True, null=True)),
                ('team_details', models.TextField(blank=True, null=True)),
                ('legal_documents', models.TextField(blank=True, null=True)),
                ('risk_assessment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_images',
                'ordering': ['order'],
            },
        ),
    ]
