# Generated by Django 6.0 on 2026-01-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_archive_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecteditrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
