# Generated by Django 6.0 on 2025-12-30 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='approval_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='request_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('WITHDRAWN', 'Withdrawn'), ('REVERSED', 'Reversed')], default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('WITHDRAWN', 'Withdrawn'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20),
        ),
    ]
