# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investment_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
