# Generated by Django 6.0 on 2025-12-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_SUBMITTED', 'Project Submitted'), ('PROJECT_APPROVED', 'Project Approved'), ('PROJECT_REJECTED', 'Project Rejected'), ('PROJECT_ARCHIVED', 'Project Archived'), ('ACCESS_REQUEST_CREATED', 'Access Request Created'), ('ACCESS_REQUEST_APPROVED', 'Access Request Approved'), ('ACCESS_REQUEST_REJECTED', 'Access Request Rejected'), ('ACCESS_REQUEST_REVOKED', 'Access Request Revoked'), ('INVESTMENT_CREATED', 'Investment Created'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DISABLED', 'User Disabled')], max_length=50)),
                ('target_type', models.CharField(choices=[('project', 'Project'), ('user', 'User'), ('access_request', 'Access Request'), ('investment', 'Investment'), ('payment', 'Payment')], max_length=50)),
                ('target_id', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
