# Generated by Django 6.0 on 2025-12-30 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLedgerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_SUBMITTED', 'Project Submitted'), ('PROJECT_APPROVED', 'Project Approved'), ('PROJECT_REJECTED', 'Project Rejected'), ('PROJECT_EDIT_REQUESTED', 'Project Edit Requested'), ('PROJECT_EDIT_APPROVED', 'Project Edit Approved'), ('PROJECT_EDIT_REJECTED', 'Project Edit Rejected'), ('ACCESS_REQUEST_CREATED', 'Access Request Created'), ('ACCESS_REQUEST_APPROVED', 'Access Request Approved'), ('ACCESS_REQUEST_REJECTED', 'Access Request Rejected'), ('INVESTMENT_REQUESTED', 'Investment Requested'), ('INVESTMENT_APPROVED', 'Investment Approved'), ('INVESTMENT_REJECTED', 'Investment Rejected'), ('INVESTMENT_PROCESSING', 'Investment Processing'), ('INVESTMENT_COMPLETED', 'Investment Completed'), ('INVESTMENT_REFUNDED', 'Investment Refunded'), ('INVESTMENT_WITHDRAWN', 'Investment Withdrawn'), ('INVESTMENT_REVERSED', 'Investment Reversed'), ('USER_BANNED', 'User Banned')], max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='projects.project')),
            ],
            options={
                'db_table': 'project_ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
