# Generated by Django 6.0 on 2026-01-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_project_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_SUBMITTED', 'Project Submitted'), ('PROJECT_APPROVED', 'Project Approved'), ('PROJECT_REJECTED', 'Project Rejected'), ('PROJECT_ARCHIVED', 'Project Archived'), ('PROJECT_EDIT_REQUESTED', 'Project Edit Requested'), ('PROJECT_EDIT_APPROVED', 'Project Edit Approved'), ('PROJECT_EDIT_REJECTED', 'Project Edit Rejected'), ('PROJECT_ARCHIVE_REQUESTED', 'Project Archive Requested'), ('PROJECT_ARCHIVE_APPROVED', 'Project Archive Approved'), ('PROJECT_ARCHIVE_REJECTED', 'Project Archive Rejected'), ('ACCESS_REQUEST_CREATED', 'Access Request Created'), ('ACCESS_REQUEST_APPROVED', 'Access Request Approved'), ('ACCESS_REQUEST_REJECTED', 'Access Request Rejected'), ('ACCESS_REQUEST_REVOKED', 'Access Request Revoked'), ('INVESTMENT_REQUESTED', 'Investment Requested'), ('INVESTMENT_APPROVED', 'Investment Approved'), ('INVESTMENT_REJECTED', 'Investment Rejected'), ('INVESTMENT_PROCESSING', 'Investment Processing'), ('INVESTMENT_COMPLETED', 'Investment Completed'), ('INVESTMENT_REFUNDED', 'Investment Refunded'), ('INVESTMENT_WITHDRAWN', 'Investment Withdrawn'), ('INVESTMENT_REVERSED', 'Investment Reversed'), ('INVESTMENT_EXPIRED', 'Investment Expired'), ('INVESTMENT_CANCELLED', 'Investment Cancelled'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('PAYMENT_WITHDRAWN', 'Payment Withdrawn'), ('PAYMENT_REVERSED', 'Payment Reversed'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DISABLED', 'User Disabled'), ('USER_BANNED', 'User Banned'), ('USER_UNBANNED', 'User Unbanned')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(choices=[('project', 'Project'), ('user', 'User'), ('access_request', 'Access Request'), ('investment', 'Investment'), ('payment', 'Payment'), ('project_edit_request', 'Project Edit Request')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projectledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('PROJECT_UPDATED', 'Project Updated'), ('PROJECT_SUBMITTED', 'Project Submitted'), ('PROJECT_APPROVED', 'Project Approved'), ('PROJECT_REJECTED', 'Project Rejected'), ('PROJECT_ARCHIVED', 'Project Archived'), ('PROJECT_EDIT_REQUESTED', 'Project Edit Requested'), ('PROJECT_EDIT_APPROVED', 'Project Edit Approved'), ('PROJECT_EDIT_REJECTED', 'Project Edit Rejected'), ('PROJECT_ARCHIVE_REQUESTED', 'Project Archive Requested'), ('PROJECT_ARCHIVE_APPROVED', 'Project Archive Approved'), ('PROJECT_ARCHIVE_REJECTED', 'Project Archive Rejected'), ('ACCESS_REQUEST_CREATED', 'Access Request Created'), ('ACCESS_REQUEST_APPROVED', 'Access Request Approved'), ('ACCESS_REQUEST_REJECTED', 'Access Request Rejected'), ('ACCESS_REQUEST_REVOKED', 'Access Request Revoked'), ('INVESTMENT_REQUESTED', 'Investment Requested'), ('INVESTMENT_APPROVED', 'Investment Approved'), ('INVESTMENT_REJECTED', 'Investment Rejected'), ('INVESTMENT_PROCESSING', 'Investment Processing'), ('INVESTMENT_COMPLETED', 'Investment Completed'), ('INVESTMENT_REFUNDED', 'Investment Refunded'), ('INVESTMENT_WITHDRAWN', 'Investment Withdrawn'), ('INVESTMENT_REVERSED', 'Investment Reversed'), ('INVESTMENT_EXPIRED', 'Investment Expired'), ('INVESTMENT_CANCELLED', 'Investment Cancelled'), ('PAYMENT_PROCESSED', 'Payment Processed'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('PAYMENT_WITHDRAWN', 'Payment Withdrawn'), ('PAYMENT_REVERSED', 'Payment Reversed'), ('USER_BANNED', 'User Banned')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projectledgerentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
